trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: prisma-cloud-compute-scan@3
  inputs:
    scanType: 'images'
    twistlockService: 'Prisma Cloud Compute Console'
    artifact: 'itresoldi/evilpetclininc.latest'